### PR TITLE
Amls 5779 - Letting Agent DES Integration

### PR DESCRIPTION
**Pull request by ajchilts**
This PR enables AMLS FE to toggle on the new EAB FE service and submit EAB payloads containing the new Letting Agents question for Client Money Protection. 

As moving to the new EAB FE service is a substantial undertaking this PR preserves the existing EstateAgentBusiness models using them for interactions with AMLS BE. Preserving these models means we preserve the current contracts between AMLS FE and AMLS BE therefore requiring less rework in order to achieve DES interactions using the new phase 3 schemas. 

I would suggest we revisit this in a separate ticket should we get time with the aim of removing the EstateAgentBusiness models all together and aligning the solution with that of the AMP journey. I deemed this to be a significant undertaking on this ticket as it became too large a piece of work particularly when attempting to feature toggle it. 

As its own piece of work down the line and without the need to feature toggle this will be much more achievable. 

NOTE: this PR will still allow us to remove all existing EstateAgentBusiness views and controllers. 

## Related / Dependant PRs?

https://github.com/hmrc/app-config-base/pull/3270

https://github.com/hmrc/amls/pull/295

Stubs branch: https://github.com/hmrc/amls-stub/tree/AMLS-5779-la

## How Has This Been Tested?

Unit, Local, toggled on, toggled off, regression when toggled off. 

## Checklist

- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [x] Build passing.
- [ ] Unit tests have full coverage.
- [ ] Unit test approach and implementation has been reviewed with QA (testers).
- [x] Requires acceptance test run.
- [x] Appropriate labels added.
- [x] RELEASE NOTES ADDED.

### CODE REVIEW

**Comment by slavvco** [comment]
test this please

**Comment by slavvco** [comment]
and compilation is failing

**Comment by ajchilts** [comment]
> Seems like there are unit tests missing for convert methods. Is the test coverage of new code high enough?

@slavvco - the covert methods are covered by a single unit test that converts the entire object and its counterparts. It would be a duplication of effort (and coverage) to add individual tests.  The Eab.scala 'conv' method has a test that covers a full convert.

**Comment by ajchilts** [comment]
> and compilation is failing

@slavvco  - Unit tests pass locally. Not sure why he PR builder failed. Will look into it.

**Pull request merged**
