### PR TITLE
Amls 4637 businessactivities controller DI

### PR DESCRIPTION
**Pull request by samzaroughmrc**
[Your pull request description here]

## Checklist

- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] Build passing.
- [ ] Unit tests have full coverage.
- [ ] Unit test approach and implementation has been reviewed with QA (testers).
- [ ] Requires acceptance test run.
- [ ] Appropriate labels added.

### CODE REVIEW

**Comment by owen-opencast** [comment]
Just talked with @ajchilts - recommendation is that we don't start adding singleton annotations until performance requires them. Can we remove them?

**Comment by slavvco** [comment]
Isn't it actually good approach to use @Singleton annotation? https://www.playframework.com/documentation/2.6.x/ScalaDependencyInjection#Singletons

**Comment by owen-opencast** [comment]
The documentation from that link recommends the use of Singletons when you have state, or when you're caching things within the class - I don't think the controllers should be caching anything, they should just be doing simple processing and forwarding of requests.

There may be a slight performance benefit from reusing a single controller object, but current recommendation is we don't use them until we need to.

**Comment by owen-opencast** [comment]
Passes spec and regression tests, merging into master.

**Pull request merged**
